settings:
  chat_format: "%luckperms_prefix%%player_name%&f: %message%"
  cooldown_message: 3
  anti_caps: true
  caps_percent: 75
  anti_link: true
  anti_spam: true
  banned_words: true

messages:
  banned_words: "&cYou can't send this message!!"
  anti_caps: "&cYou're using caps too much!"
  anti_link: "&cYou can't send links within the server!"
  anti_spam: "&cPlease wait before sending another message. (%time%s)"
  anti_botspam: "&cYou must move first to be able to write in chat or execute a command."
  usage_message: "&cUse: /msg <player> <message>"
  usage_reply: "&cUse: /r <message>"
  dont_have_conversations: "&cYou don't have any conversations going on."
  player_not_found: "&cPlayer not found."
  format_pm_sender: "&7(A &f%receiver%&7) &f%message%"
  format_pm_receiver: "&7(Da &f%sender%&7) &f%message%"
  cant_send_yourself: "&cYou can't send a message to yourself."
banned_words:
  - "negro"
  - "negra"
  - "negri"
  - "frocio"
  - "frocia"
  - "froci"
  - "gay"
  - "lesbica"
  - "lesbiche"
  - "finocchio"
  - "finocchi"
  - "coglione"
  - "coglioni"
  - "bastardo"
  - "bastardi"
  - "ritardato"
  - "ritardati"
  - "tumorare"
  - "cancro"
  - "cancri"
  - "tumori"
  - "mongolo"
  - "mongola"
  - "hitler"
  - "ebola"
  - "malaria"
  - "autistico"
  - "autistica"
  - "down"
  - "stronzo"
  - "faggot"
  - "checca"
  - "madonna"
  - "andicappato"
  - "puttana"
  - "vaffanculo"
  - "ricchione"
  - "esplodi"
  - "suicidati"
  - "coral"
  - "aquarius"
  - "tempest"
  - "feargames"
  - "waraccademy"
  - "pvpclub"
  - "mcpvp"
  - "lyzard"
  - "nigger"
  - "nibber"
  - "diabete"
  - "scabbia"
  - "stupro"
  - "stupra"
  - "pompino"
  - "pompini"
  - "ciuccia"
  - "suca"
  - "ictus"
  - "epatite"
  - "swat"
  - "ddoss"
  - "doss"
  - "ddos"
  - "dox"
  - "ammazzati"
  - "ucciditi"
  - "rape"
  - "terrone"
  - "obeso"
  - "ciccione"
  - "impiccati"
  - "kys"
  - "ricchiu"
  - "mussolini"
  - "fascismo"
  - "fascista"
  - "fascio"
  - "nazista"
  - "nazismo"
  - "nazi"
  - "dio"
  - "porco"
  - "cazzo"
  - "cazzi"
  - "mongoplettico"
  - "menomato"
  - "menomati"